apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsduniya
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsduniya
  template:
    metadata:
      labels:
        app: devopsduniya
    spec:
      containers:
      - name: devopsduniya
<<<<<<< HEAD
        image: gcr.io/devopsduniya/devopsduniya:52
=======
        image: gcr.io/devopsduniya/devopsduniya:52
>>>>>>> 01d55fdd9ded34c94e026cb99930ab52552cd0b3
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10