apiVersion: v1
kind: Service
metadata:
  name: devopsduniya-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
